// <auto-generated />
using System;
using Corporate_training_management_system.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Corporate_training_management_system.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223081808_joinTableAdded")]
    partial class joinTableAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Corporate_training_management_system.Repository.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Ahmedabad",
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Ahmedabad",
                            Name = "HR"
                        });
                });

            modelBuilder.Entity("Corporate_training_management_system.Repository.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "crunal@company.com",
                            Name = "Krunal"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "charvin@company.com",
                            Name = "Charvin"
                        });
                });

            modelBuilder.Entity("Corporate_training_management_system.Repository.Models.EmployeeTrainingProgram", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingProgramId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EnrollmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("EmployeeId", "TrainingProgramId");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("EmployeeTrainingPrograms");
                });

            modelBuilder.Entity("Corporate_training_management_system.Repository.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("ExpertiesLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpertiesLevel = "[\".NET\",\"C#\"]",
                            Name = "Akshay"
                        });
                });

            modelBuilder.Entity("Corporate_training_management_system.Repository.Models.TrainingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainingPrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationInDays = 20,
                            StartDate = new DateOnly(2026, 2, 23),
                            Title = ".NET",
                            TrainerId = 1
                        });
                });

            modelBuilder.Entity("Corporate_training_management_system.Repository.Models.Employee", b =>
                {
                    b.HasOne("Corporate_training_management_system.Repository.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Corporate_training_management_system.Repository.Models.EmployeeTrainingProgram", b =>
                {
                    b.HasOne("Corporate_training_management_system.Repository.Models.Employee", "Employee")
                        .WithMany("EmployeeTrainingPrograms")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Corporate_training_management_system.Repository.Models.TrainingProgram", "TrainingProgram")
                        .WithMany("EmployeeTrainingProgram")
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("Corporate_training_management_system.Repository.Models.TrainingProgram", b =>
                {
                    b.HasOne("Corporate_training_management_system.Repository.Models.Trainer", "Trainer")
                        .WithMany("TrainingPrograms")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Corporate_training_management_system.Repository.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Corporate_training_management_system.Repository.Models.Employee", b =>
                {
                    b.Navigation("EmployeeTrainingPrograms");
                });

            modelBuilder.Entity("Corporate_training_management_system.Repository.Models.Trainer", b =>
                {
                    b.Navigation("TrainingPrograms");
                });

            modelBuilder.Entity("Corporate_training_management_system.Repository.Models.TrainingProgram", b =>
                {
                    b.Navigation("EmployeeTrainingProgram");
                });
#pragma warning restore 612, 618
        }
    }
}
